services:
  db:
    image: postgres:13
    container_name: redmine-db
    environment:
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: redmine
      POSTGRES_DB: redmine
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  redmine-migrate:
    image: redmine:5.0
    container_name: redmine-migrate
    depends_on:
      - db
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_DB_DATABASE: redmine
      REDMINE_SECRET_KEY_BASE: "changeme-secret"
    command: >
      bash -c "bundle exec rake db:migrate && touch /tmp/migrated && tail -f /dev/null"
    networks:
      - backend

  redmine-app:
    image: redmine:5.0
    depends_on:
      - db
      # opcional: asegurarte de que migrations corran primero
      - redmine-migrate
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_DB_DATABASE: redmine
      REDMINE_SECRET_KEY_BASE: "changeme-secret"
    networks:
      - backend
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redmine.rule=Host(`redmine.localhost`)"
      - "traefik.http.routers.redmine.entrypoints=websecure"
      - "traefik.http.routers.redmine.tls=true"
      - "traefik.http.services.redmine.loadbalancer.server.port=3000"

  traefik:
    image: traefik:v2.10
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-certificates:/letsencrypt
    networks:
      - traefik

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - backend

volumes:
  db-data:
  traefik-certificates:

networks:
  backend:
  traefik:
